apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  MYSQL_USER : cm9vdAo=
  MYSQL_PASSWORD : cm9vdAo=
  MYSQL_ROOT_PASSWORD:  cm9vdAo=

  MYSQL_ALLOW_EMPTY_PASSWORD:  cm9vdAo=

  MYSQL_RANDOM_ROOT_PASSWORD:  cm9vdAo=


  WORDPRESS_DB_USER:  cm9vdAo=
  WORDPRESS_DB_PASSWORD:  cm9vdAo=
       