apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
# | POSTGRES web username
  POSTGRES_USER : cm9vdAo=

 #  | POSTGRES web password          
  POSTGRES_PASSWORD : cm9vdAo=