apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
# | mongo-express web username
  ME_CONFIG_BASICAUTH_USERNAME : cm9vdAo=

 #  | mongo-express web password          
  ME_CONFIG_BASICAUTH_PASSWORD : cm9vdAo=